apiVersion: v1
entries:
  cms:
  - apiVersion: v2
    appVersion: v1
    created: "2022-11-13T10:01:53.55971264Z"
    description: Contest Management System
    digest: aa158ed2b7b5ff83fcf17b5bd9ebe1f47c7a16ec1f099ead3962b123e6a1fb56
    name: cms
    type: application
    urls:
    - cms-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: v1
    created: "2022-11-13T10:01:53.55895293Z"
    description: Contest Management System
    digest: 30a196b90197773c1e5ee61144950dfb1077bd1962625e0552da77362c20a350
    name: cms
    type: application
    urls:
    - cms-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: v1
    created: "2022-11-13T10:01:53.55817092Z"
    description: Contest Management System
    digest: 0a9b0cc5133010a1c08a2a4362dd777176786de69753d74da528dfebf899fae1
    name: cms
    type: application
    urls:
    - cms-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: v1
    created: "2022-11-13T10:01:53.557387909Z"
    description: Contest Management System
    digest: 43ed889505885f0436b94f90e76073738cd2c89fd19352cb7955d6f5d1464b3d
    name: cms
    type: application
    urls:
    - cms-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: v1
    created: "2022-11-13T10:01:53.556598799Z"
    description: Contest Management System
    digest: cfa421d2fcdfe9b0c176fdf601a4a297e19e5c51a8230c2728dd710fe3b19fc8
    name: cms
    type: application
    urls:
    - cms-0.0.1.tgz
    version: 0.0.1
generated: "2022-11-13T10:01:53.555566586Z"
